# Generated by Django 3.2.5 on 2021-07-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrition',
            name='size_ml',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='size_oz',
        ),
    ]
