# Generated by Django 3.2.5 on 2021-07-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210717_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='size_ml',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='size_oz',
            field=models.IntegerField(default=0),
        ),
    ]
